### ISSUE TITLE
Errors running Armbian  on Olimex SOM204 

### ISSUE THREAD

**Issue by Muriukidavid** [artizirk/python-axp209#4]
I installed everything correctly, but at first I was getting permission denied errors. So I created a group calle i2c and changed owner of i2c-0 device to that, then added my user to that group, and a udev rule to make sure every time an i2c device is added, it's also added to that group. 
Now when I try the examples give I get:

    axp209
    Traceback (most recent call last):
    File "/home/david/.local/bin/axp209", line 11, in <module>
    sys.exit(main())
    File "/home/david/.local/lib/python3.6/site-packages/axp209.py", line 236, in main
    axp = AXP209()
    File "/home/david/.local/lib/python3.6/site-packages/axp209.py", line 127, in __init__
    self.adc_enable1 = 0xc3
    File "/home/david/.local/lib/python3.6/site-packages/axp209.py", line 163, in adc_enable1
    self.bus.write_byte_data(AXP209_ADDRESS, ADC_ENABLE1_REG, flags)
    File "/home/david/.local/lib/python3.6/site-packages/smbus2/smbus2.py", line 391, in write_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
    OSError: [Errno 5] Input/output error

When I try to read write smbus without this module, it works:

    from smbus2 import SMBus  
    bus = SMBus(1, force=True)  
    bus.read_byte_data(0x34,00)  
    192  
    bus.read_byte_data(0x34,0x01)  
    48
I am able to read the registers without a problem. I just don't know where the error is coming from.

**Comment by artizirk** [comment]
It could be that some kernel updates have bricked something. I can try to reproduce this next week on my Cubietruck board.

Are you running the board with the default 4.19 kernel that comes with Armbian or are you running some other customizations?

**Comment by Muriukidavid** [comment]
I am running official kernel, no kernel customization 

    uname -r
    4.19.38-sunxi

**Comment by Muriukidavid** [comment]
It is an ioctl input/ouput error, doesn't seem related to smbus2

**Comment by Muriukidavid** [comment]
I have figured it out. The default bus is 0, but AXP is in bus 1 on the Olimex board. 

    >>> axp = AXP209(1)
    >>> axp.battery_voltage
    4050.2000000000003
